// const STATUS_OK = 200;
// const STATUS_CREATED = 201;
// const STATUS_BAD_REQUEST = 400;
// const STATUS_UNAUTHORIZED = 401;
// const STATUS_FORBIDDEN = 403;
// const STATUS_NOT_FOUND = 404;
// const STATUS_CONFLICT = 409;
// const STATUS_INTERNAL_SERVER_ERROR = 500;

const STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

module.exports = {
  STATUS
};

// module.exports = {
//   STATUS_OK,
//   STATUS_CREATED,
//   STATUS_BAD_REQUEST,
//   STATUS_UNAUTHORIZED,
//   STATUS_NOT_FOUND,
//   STATUS_INTERNAL_SERVER_ERROR,
//   STATUS_CONFLICT,
// };
